name: PigRaceHEXA
version: '${project.version}'
main: org.hexa.pigracehexa.PigRaceHEXA
api-version: '1.20'
commands:
  pigstart:
    usage: /<command>
    description: Spawnea los cerdos
    permission: pig.start
  pigstop:
    usage: /<command>
    description: Despawnea a los cerdos
    permission: pig.stop
  pigcheckpoint:
    usage: /<command>
    description: Crea checkpoints
    permission: pig.checkpoint
